name: Publish image to ACR and deploy to dev environment

on:
  workflow_call

env:
  IMAGE_NAME: dadjokes

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.previoustag.outputs.tag }}
          file: AZ204-DadJokes/Dockerfile
          
  call-deploy-workflow:
    uses: ./.github/workflows/Deploy_ReusableWorkflow.yml
    secrets: inherit
    with:
      environment-name: dev
