name: "[Manual trigger] Deploy to test environment"

on:
  workflow_dispatch

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/Deploy_ReusableWorkflow.yml
    secrets: inherit
    with:
      environment-name: test
