name: "001 [Manual trigger] Publish image to ACR and deploy to dev environment the latest app version"

on:
  workflow_dispatch
    
jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/CreateImageAndDeployToDev.yml
    secrets: inherit
